// This is an automatically generated file. Please do not edit this file directly.
'use server';

/**
 * @fileOverview A flow that summarizes LinkedIn work experience.
 *
 * - summarizeLinkedInExperience - A function that summarizes work experience from a LinkedIn profile.
 * - LinkedInSummaryInput - The input type for the summarizeLinkedInExperience function.
 * - LinkedInSummaryOutput - The return type for the summarizeLinkedInExperience function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const LinkedInSummaryInputSchema = z.object({
  linkedinProfileUrl: z.string().describe('The URL of the LinkedIn profile.'),
  workExperienceSection: z.string().describe('The work experience section of the LinkedIn profile.'),
});
export type LinkedInSummaryInput = z.infer<typeof LinkedInSummaryInputSchema>;

const LinkedInSummaryOutputSchema = z.object({
  summary: z.string().describe('A concise summary of the work experience.'),
});
export type LinkedInSummaryOutput = z.infer<typeof LinkedInSummaryOutputSchema>;

export async function summarizeLinkedInExperience(input: LinkedInSummaryInput): Promise<LinkedInSummaryOutput> {
  return linkedInSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'linkedInSummaryPrompt',
  input: {schema: LinkedInSummaryInputSchema},
  output: {schema: LinkedInSummaryOutputSchema},
  prompt: `You are a professional resume writer. Summarize the following work experience from a LinkedIn profile into a concise and compelling overview for an "About Me" section of a portfolio.  The summary should highlight key accomplishments and responsibilities.

LinkedIn Profile URL: {{{linkedinProfileUrl}}}
Work Experience Section:
{{{workExperienceSection}}}`,
});

const linkedInSummaryFlow = ai.defineFlow(
  {
    name: 'linkedInSummaryFlow',
    inputSchema: LinkedInSummaryInputSchema,
    outputSchema: LinkedInSummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
